config/routes.rb
Rails.application.routes.draw do
  get 'messages_list' => 'messages#index'

  get 'messages/show'

  get 'messages/new'

  get 'messages/create'

  get 'sent_messages' => 'messages#index2'

  resources :messages

  resources :friendships
  get 'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  get 'log_out' => 'sessions#destroy'
  get 'profile' => 'users#show'
  get 'users/new'

  resources :users
  get 'sign_up' => 'users#new'  

  root 'welcome#index'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: 'User'
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id'
	belongs_to :recipient, :class_name =>'User', :foreign_key => 'recipient_id'

	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :friendships
	has_many :friends, through: :friendships
	has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
	has_many :recieved_messages, :class_name => 'Message', :foreign_key => 'recipient_id'
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :signed_in?, :current_user

  def signed_in?
  	current_user
  end

  def current_user  	  	
    @current_user ||= User.find_by(id: session[:user_id])
  end 

  def require_authenticate
    redirect_to log_in_path, flash: {error: "Please login"} unless signed_in?
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  #before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to profile_path, notice: 'Friendship was successfully created.' }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to profile_path, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :create, :destroy)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_authenticate, only: [:index, :index2, :show, :new, :create]
  def index
  	@messages = Message.where(recipient: current_user)
  end

  def index2
    @messages = Message.where(sender: current_user)
  end

  def show
  end

  def new
  	@message = Message.new  	
  end

  def create  
      recipient = User.find(params[:message][:recipient])
      Message.create(sender: current_user, recipient: recipient, body: params[:message][:body])
      redirect_to messages_list_path, notice: 'message successfully sent.' 
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new   
  end

  def create
  	user = User.find_by_email(params[:session][:email])
  	if user && user.authenticate(params[:session][:password])      
      session[:user_id] = user.id  		
      redirect_to users_path, flash: {notice: "You have logged in"} 		
  	else  		
  		render "new"
  	end
  end 

  def destroy
    session.clear
    redirect_to root_path, flash: {notice: "You have logged out"}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_authenticate, only: [:show, :index]
  
  def new
  	@User = User.new
  end

  def show
    @user = current_user
  end

  def index
  	@Users = User.all    
  end


  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to log_in_path
  	else
  		render 'new'
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email,:password,:password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_link(link_text,link_path)
		class_name = current_page?(link_path) ? "active" : ""
		content_tag :li, class: class_name do
			content_tag :a do
				link_to link_text, link_path
			end
		end 
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/_form.html.erb
<%= simple_form_for(@friendship) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :friend_id %>
    <%= f.input :create %>
    <%= f.input :destroy %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.create %></td>
        <td><%= friendship.destroy %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @friendship.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @friendship.destroy %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>Coderchat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="/" class="brand-logo">CoderChat</a>
      <ul class="right hide-on-med-and-down">
        <% if signed_in? %>
          <li><%= active_link "Incomming Messages", messages_list_path %></li>
          <li><%= active_link "Send Message", messages_new_path %></li>
          <li><%= active_link "Sent Messages", sent_messages_path %></li>
          <li><%= active_link "My Friends", profile_path %></li>
          <li><%= active_link "Add Friends", users_path%></li>
          <li><%= active_link "Log Out", log_out_path %></li>
        <% else %>
          <li><%= active_link "Sign Up", sign_up_path %></li>
          <li><%= active_link "Log In", log_in_path %></li>
        <% end %>
      </ul>

      <ul id="nav-mobile" class="side-nav">
       <% if signed_in? %>
          <li><%= active_link "Incomming Messages", messages_list_path %></li>
          <li><%= active_link "Send Message", messages_new_path %></li>
          <li><%= active_link "Sent Messages", sent_messages_path %></li>
          <li><%= active_link "My Friends", profile_path %></li>
          <li><%= active_link "Add Friends", users_path%></li>
          <li><%= active_link "Log Out", log_out_path %></li>
        <% else %>
          <li><%= active_link "Sign Up", sign_up_path %></li>
          <li><%= active_link "Log In", log_in_path %></li>
        <% end %>
      </ul>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <div class="parallax"><%= image_tag 'background.jpg', alt: 'coder chat background' %></div>
</div>
  

  <footer class="page-footer teal">
   <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">CoderChat Bio</h5>
          <p class="grey-text text-lighten-4">CoderChat for coders to chat!</p>
        </div>     
      </div>
    </div>
  <div class="footer-copyright">
    <div class="container">
      Made By <%= link_to "CoderChat", '/' %>
      </div>
    </div>
  </footer>
</body>
  <script type="text/javascript">
    (function($){
      $(function(){

        $('.button-collapse').sideNav();
        $('.parallax').parallax();

      }); // end of document ready
    })(jQuery); // end of jQuery name space
  </script>
  <script type="text/javascript">
    $(document).ready(function() {
        $('select').material_select();
    });
    // Initialize collapse button
      $(".button-collapse").sideNav();
      // Initialize collapsible (uncomment the line below if you use the dropdown variation)
      //$('.collapsible').collapsible();        
  </script>
</html>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<h4 class="header center teal-text text-lighten-2">Message List</h4>
<% if @messages %>
<%= @messages.each do |message| %>
<div class = 'row'>
<div class = 'col s12'>
  <div class='card blue-grey darken-1'>    
        <div class=card-content white-text>
          <span class = 'card-title'>Sender: <%= message.sender.name %></span><br>
          <span class = 'card-title'>Recipient: <%= message.recipient.name %></span>
          <p>Sent At:<%= message.created_at.strftime("%A, %B %d, %H:%M") %></p>
          <p><%= message.body %></p>
        </div>       
  </div>
  </div>
</div>
  
  <% end %>
  <% end %>  

app/views/messages/index2.html.erb
<h4 class="header center teal-text text-lighten-2">Sent Messages</h4>
<% if @messages %>
<% @messages.each do |message| %>
<div class = 'row'>
<div class = 'col s12'>
  <div class='card blue-grey darken-1'>    
        <div class=card-content white-text>
          <span class = 'card-title'> Recipient: <%= message.recipient.name %></span>
          <p>Sent At:<%= message.created_at.strftime("%A, %B %d, %H:%M") %></p>
          <p>Message Content: <%= message.body %></p>
        </div>       
  </div>
  </div>
</div>
  
  <% end %>
  <% end %>  

app/views/messages/new.html.erb
<h4 class="header center teal-text text-lighten-2">Send New Message</h4>
<div class="form-group lime-text text-accent-4">	
	<%= simple_form_for @message do |f| %>		
		
		<%= f.input :recipient do %>			
	  		<%= f.select :recipient, current_user.friends.collect {|f| [f.name, f.id] }, label: "recipient", include_blank: true,class: 'input-field col s6' %>
		<% end %>	
	
		<%= f.input :body, label: "Message", class: 'input-field col s6' %>
		
		<div class="row center">
		<%= f.button :submit, "Send", class: 'btn btn-primary' %>
		<div class="row center">
	<% end %>
</div>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>

app/views/users/index.html.erb
<h1 class="header center teal-text text-lighten-2">User List</h1>
<div class="collection">
	<% @Users.each do |user| %>
		<%= link_to friendships_path(friend_id: user), :method => :post, 
		class: "collection-item" do %>
		<%= user.name %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span class = "left-align">Add Friend</span>
		<% end %>

	<% end %>
	
</div>

app/views/users/new.html.erb
<h1 class="header center teal-text text-lighten-2">Sign Up</h1>
<div class="form-group lime-text text-accent-4">	
	<%= simple_form_for @User do |f| %>
		<%= f.input :name, label: "name", class: 'input-field col s6' %>
		<%= f.input :email, label: "email", class: 'input-field col s6'   %>
		<%= f.input :password, label: "password", class: 'input-field col s6 '%>
		<%= f.input :password_confirmation, label: "password again!", class: 'input-field col s6' %>
		<div class="row center">
		<%= f.button :submit, "Sign Up", class: 'btn btn-primary' %>
		<div class="row center">
	<% end %>
</div>

app/views/users/show.html.erb
<h4 class="header center teal-text text-lighten-2">My Friend List</h4>
<ul class="collection with-header teal-text text-darken-2">
	 <li class="collection-header"><strong>All added friends</strong></li>
	<% for user in @user.friends %>
		<li class ='collection-item'>
			<%= user.name %>			
		</li>
	<% end %>
</ul>

app/views/welcome/index.html.erb
<br><br>	
  <h1 class="header center teal-text text-lighten-2">Chat for Coders</h1>
  <div class="row center">
    <h5 class="header col s12 light">Chat for coders to work together!</h5>
  </div>
  <div class="row center">
    <a href="/sign_up" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
  </div>
 <br><br>